# Generated by Django 4.2.1 on 2023-05-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_userprofile_cart_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cart',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cart',
            field=models.ManyToManyField(blank=True, to='catalog.product'),
        ),
    ]
